// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

// TODO: thinking about using Hono for my BE. Then I can get
// the types from the BE directly. Making this file redundant.

export type BaseEntity = {
  id: string
  createdAt: number
}

export type Entity<T> = {
  [K in keyof T]: T[K]
} & BaseEntity

export type User = Entity<{
  id: string
  firstName: string
  lastName: string
  email: string
  username: string
}>

export type AuthResponse = {
  jwt: string
  data: User
}
