// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

// TODO: thinking about using Hono for my BE. Then I can get
// the types from the BE directly. Making this file redundant.

export type BaseEntity = {
  id: string
}

export type Entity<T> = {
  [K in keyof T]: T[K]
} & BaseEntity

export type User = Entity<{
  id: string
  firstName: string
  lastName: string
  email: string
  username: string
}>

export type AuthResponse = {
  jwt: string
  data: User
}

export type Vote = Entity<{
  memberId: string
  voteType: 'Upvote' | 'Downvote'
}>

export type Comment = Entity<{
  memberId: string
  text: string
  parentCommentId: string | null
}>

export type Post = Entity<{
  memberId: string
  postType: 'text' | 'link'
  title: string
  content: string
  dateCreated: string
  memberPostedBy: {
    user: Omit<User, 'id'>
  }
  votes: Array<Vote>
  comments: Array<Comment>
}>
